// FOR LOGIN PAGE
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const GET_DATA = 'GET_DATA'
export const REQUEST_LOGIN = 'REQUEST_LOGIN'
export const FAILURE_LOGIN = 'FAILURE_LOGIN'
export const FETCH_ALL_LENDER_DATA = 'FETCH_ALL_LENDER_DATA'